---
language: ruby
cache: bundler
rvm:
  - 3.4
  - 3.3
  - 3.0
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
before_install:
  - gem install bundler
  - rm Gemfile.lock
script:
  - bin/rspec
jobs:
  fast_finish: true
  include:
    - rvm: 2.7.0
      name: Rubocop
      script:
        - bundle info rubocop
        - bin/rubocop
